version: 1.0.{build}
image: Visual Studio 2019

environment:
  nodejs_version: "14"

branches:
  only:
    - main 

cache: 
  - node_modules 

install:
  - ps: npm install 

build: off

build_script:
  - ps: npm run build 

deploy_script:
  - git config --global credential.helper store
  - git config --global user.email roro425052@gmail.com
  - git config --global user.name JobGoog
  - npx gh-pages -d dist -r "https://$GITHUB_TOKEN@github.com/JobGoog/DOM.git" -u "jobgoog <roro425052@gmail.com>" 

