version: 1.0.{build}
image: Visual Studio 2019

environment:
  nodejs_version: "14"

branches:
  only:
    - main # ветка git

cache: 
  - node_modules # кеширование

install:
  - ps: npm install # команда установки зависимостей

build: off

build_script:
  - ps: npm run build # команда сборки

deploy_script:
  - git config --global credential.helper store
  - git config --global user.email roro425052@gmail.com
  - git config --global user.name JobGoog
  - echo "https://$GITHUB_TOKEN:x oauth-basic@github.com" > ~/.git-credentials
  - npx gh-pages -d dist -u "appveyor-bot <roro425052>"