version: 1.0.{build}
image: Visual Studio 2019

environment:
  nodejs_version: "14"

branches:
  only:
    - main # ветка git

cache: 
  - node_modules # кеширование

install:
  - ps: npm install # команда установки зависимостей

build: off

build_script:
  - ps: npm run build # команда сборки

deploy_script: # скрипт развёртывания
  - ps: |
      if ($env:APPVEYOR_REPO_BRANCH -eq 'main' -and $env:APPVEYOR_PULL_REQUEST_NUMBER -eq $null) {
        git config --global user.email "ci@appveyor.com"
        git config --global user.name "AppVeyor"
        git clone https://$env:GITHUB_TOKEN@github.com/JobGoog/DOM.git out
        cd out
        if (git rev-parse --verify gh-pages) {
          git checkout gh-pages
        } else {
          git checkout --orphan gh-pages
        }
        Remove-Item * -Recurse -Force
        Copy-Item ..\dist\* . -Recurse -Force
        git add .
        git commit -m "Update GitHub Pages [skip ci]"
        git push origin HEAD:refs/heads/gh-pages --force
      } 

