version: 1.0.{build}
image: Visual Studio 2019

environment:
  nodejs_version: "14"

install:
  - ps: npm install

build_script:
  - ps: npm run build

after_build:
  - ps: |
      git clone --quiet --branch=gh-pages "https://%GITHUB_TOKEN%@github.com/JobGoog/DOM.git" gh-pages
      Set-Location gh-pages
      Remove-Item * -Recurse -Force
      Copy-Item ..\dist\* . -Recurse
      git add --all .
      git commit -m "Deploy to GitHub Pages [skip ci]"
      git push --force origin gh-pages
