version: 1.0.{build}
image: Visual Studio 2019

environment:
  nodejs_version: "14" 

install:
  - ps: npm install

build_script:
  - ps: npm run build

artifacts:
  - path: dist
    name: build

deploy_script:
  - ps: |
      if ($env:APPVEYOR_REPO_BRANCH -eq 'main' -and $env:APPVEYOR_PULL_REQUEST_NUMBER -eq $null) {
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git clone --branch=gh-pages https://%GITHUB_TOKEN%@github.com/JobGoog/DOM.git out
        cd out
        del * /Q
        copy ..\dist\* . /Y
        git add .
        git commit -m "Update GitHub Pages [skip ci]"
        git push origin gh-pages
      }
