version: 1.0.{build}
image: Visual Studio 2019

environment:
  nodejs_version: "14"

install:
  - ps: npm install

build_script:
  - ps: npm run build

after_build:
  - ps: |
      git clone --quiet "https://$env:GITHUB_TOKEN@github.com/JobGoog/DOM.git" gh-pages
      Set-Location gh-pages
      git checkout gh-pages 2>$null
      if ($LASTEXITCODE -ne 0) {
          git checkout --orphan gh-pages
      }
      Remove-Item * -Recurse -Force
      Copy-Item ..\dist\* . -Recurse
      git config user.email "roro425052@gmail.com"
      git config user.name "JobGoog"
      git add --all .
      git commit -m "Deploy to GitHub Pages [skip ci]"
      git push --force "https://$env:GITHUB_TOKEN@github.com/JobGoog/DOM.git" HEAD:gh-pages
