version: 1.0.{build}
image: Visual Studio 2019

environment:
  nodejs_version: "14"

branches:
  only:
    - main 

cache: 
  - node_modules 

install:
  - ps: npm install 

build: off

build_script:
  - ps: npm run build 

deploy_script:
  - git config --global credential.helper store
  - git config --global user.email roro425052@gmail.com
  - git config --global user.name JobGoog
  - echo "https://$GITHUB_TOKEN:x oauth-basic@github.com" > $HOME/.git-credentials
  - npx gh-pages -d dist -u "jobgoog <roro425052@gmail.com>"